apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-2
  name: ms-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ms-2
    spec:
      containers:
        - image: gcr.io/savvy-temple-269019/github.com/oscargonzalezmartinez/gke-2-ms-2
          imagePullPolicy: IfNotPresent
          name: ms-2
          volumeMounts:
          - name: maven-repo
            mountPath: /root/.m2
      volumes:
       - name: maven-repo
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-2
  name: ms-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ms-2
    spec:
      containers:
        - image: gcr.io/savvy-temple-269019/github.com/oscargonzalezmartinez/gke-2-ms-2
          imagePullPolicy: IfNotPresent
          name: ms-2
          volumeMounts:
          - name: maven-repo
            mountPath: /root/.m2
      volumes:
       - name: maven-repo