apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-2
  name: ms-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ms-2
    spec:
      containers:
        - image: gcr.io/savvy-temple-269019/github.com/oscargonzalezmartinez/gke-2-ms-2
          imagePullPolicy: IfNotPresent
          name: ms-2
          volumeMounts:
          - name: maven-repo
            mountPath: /root/.m2
          livenessProbe:
             httpGet:
               path: /actuator/health
               port: 8080
             initialDelaySeconds: 8
             periodSeconds: 3            
      volumes:
       - name: maven-repo
         persistentVolumeClaim:
          claimName: maven-repo-vc
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: ms-2
  name: ms-2-hpa-4qft
  namespace: default
spec:
  maxReplicas: 1
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-2
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: ms-2
  name: ms-2
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
     - port: 80
       protocol: TCP
       targetPort: 8080
  selector:
    app: ms-2
  sessionAffinity: None
  type: LoadBalancer