apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-1
  name: ms-1
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ms-1
    spec:
      containers:
        - image: gcr.io/savvy-temple-269019/github.com/oscargonzalezmartinez/gke-2-ms-1
          imagePullPolicy: IfNotPresent
          name: ms-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: ms-1
  name: ms-1-hpa-z4ep
  namespace: default
spec:
  maxReplicas: 2
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-1
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: ms-1
  name: ms-1-service
  namespace: default
spec:
  clusterIP: 10.0.9.188
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30417
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: ms-1
  sessionAffinity: None
  type: LoadBalancer
